CREATE TABLE IF NOT EXISTS products(
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" varchar(255),
    "price" INTEGER NOT NULL,
    "quantity" INTEGER NOT NULL,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);